filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /var/lib/docker/containers/*/*.log
  multiline.type: json
  multiline.line_pattern: '^\{'

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
  - add_fields:
      target: taskflow
      fields:
        environment: local
        app: taskflow

output.logstash:
  hosts: ["logstash:5044"]

logging.level: debug
