name: Docker Build (no push)

on:
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"
      - "backend/**"
      - "docker-compose*.yml"

concurrency:
  group: docker-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      security-events: write
    steps:
      - uses: actions/checkout@v6
      - uses: docker/setup-buildx-action@v4

      - name: Build frontend (no push)
        uses: docker/build-push-action@v7
        with:
          load: true
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          tags: taskflow-frontend:ci
          build-args: |
            APP_VERSION=ci
            GIT_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build backend (no push)
        uses: docker/build-push-action@v7
        with:
          load: true
          context: ./backend
          file: ./backend/Dockerfile
          push: false
          tags: taskflow-backend:ci
          build-args: |
            APP_VERSION=ci
            GIT_SHA=${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Trivy Security Scan Backend
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: taskflow-backend:ci
          format: sarif
          exit-code: '0'
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          output: trivy-backend.sarif

      - name: Run Trivy Security Scan Frontend
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: taskflow-frontend:ci
          format: sarif
          exit-code: '0'
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          output: trivy-frontend.sarif

      - name: Upload Backend Trivy Results
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-backend.sarif
          category: trivy-backend

      - name: Upload Frontend Trivy Results
        if: always()
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy-frontend.sarif
          category: trivy-frontend


